In [1]:
import numpy as np
import pandas as pd

In [2]:
MOVIE_CSV = r"Dataset/tmdb_5000_movies.csv"
CREDITS_CSV = r"Dataset/tmdb_5000_credits.csv"

In [3]:
movies = pd.read_csv(MOVIE_CSV)
credits = pd.read_csv(CREDITS_CSV)

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
## We are interested in cast and crew of the movie
## Hence, we will merge both data-frames

merged_movies = movies.merge(credits, on='title')
merged_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
## Now, we have 23 columns, as movie has 20 columns and credits has 4 columns

## Theortically, following are some important features of movie:

### i) Budget: The price of making a movie. Often a more budget film attracts good ratings.
### ii) Genre: Usually tells you the category or flavour of the movie.
### iii) Homepage: Movie's homepage may have negligible effect on how the movie is.
### iv) keywords: are words which user will remember related to something in order to later on search for
###  v) Language count: looking for which movie's language, let's check it below

In [8]:
merged_movies['original_language'].value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: count, dtype: int64

<h3>
    From above, the movies with English are huge in numbers. It is biased towards the English language, hence, we will consider the 'title' of movie to be recommended, rather than the 'original_title', because original title may contain languages like Hindi, etc.
</h3>

In [9]:
### vi) 'title' of the movie, as it will be in English Language
### vii) We will also consider the summary or overview of the movie, considering that similar overview or summary will have similar likliness
### viii) Popularity: Can be a good measure for determininig the likliness of a user may watching the movie. 
###                   Because it is a numeric value, it will not sit by together in recommendation. Hence, we will not use it.
### ix) Production Companies: We don't recommend people movies based on production companies or production houses.
### x) production_countries: We again don't bother about the country where the movie was shooted
### xi) release_date: It makes sense, as some people might like movies from 80s or 90s, some people might like 2000s, 2010s, etc. For now, release date is not considered.
###                   We can think of incorporating the release_date of the movie later on
### xii) revenue: Usually it is not considered for user likliness.
### xiii) runtime: Again, cannot be considered for user likliness.
### xiv) spoken_languages: We will again not consider them
### xv) status: released or going_to_come, again, not considered for likliness
### xvi) tagline: It is textual, but the problem is, it just showcases the moto in the movie, in which the information is very brief. Hence, we will not keep it.
### xvii) vote_average: It is a numerical column, so, we are skipinig it.
### xviii) movie_id: It is kept already.
### xix) cast: May influence people to watch a movie based on the actors.
### xx) crew: We will keep it as it contains the information about the director, which nowadays people like to look for.

In [10]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [11]:
extracted_movie_features = merged_movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [12]:
extracted_movie_features.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

<h2>
    Above is the data on which we will be working on.
</h2>
<h2>
    Dataframe that we finally want from the above ones should have the following columns: movie_id, title and tags.
</h2>
<h2>
    genres, keywords, cast & crew are in key: value pair forms. We will process it.
</h2>
<h2>
    We will take only first 3 cast members, and director from crew.
</h2>

In [13]:
# # Checking for missing data

extracted_movie_features.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [14]:
# # As there are only 3 missing values in th overview, we will just drop them.

extracted_movie_features.dropna(inplace=True)

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\2789489063.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features.dropna(inplace=True)

In [15]:
## Checking again whether there are any null values or not

extracted_movie_features.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [16]:
## Checking whether any duplicate values are present

extracted_movie_features.duplicated().sum()

0

In [17]:
## Extracting the first row from the pandas

extracted_movie_features.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

<h3>
    The above is in list of dictionaries. We want to bring the whole above thing into the following format:
</h3>
<h4>
    [ 'Action', 'Adventure', 'Fantasy', 'Science Fiction' ]
</h4>

In [18]:
## In python, there is a module named 'ast' which has a method name 'literal_eval'
## The function of literal_eval is to convert the string of list of dictionaries to just list of 
## dictionaries.

In [19]:
import ast

In [20]:
type(extracted_movie_features.iloc[0].genres)

str

In [21]:
## We will create a function which will give us a list of values
## Parameters: list of dictionaries, name of the key

def extract_values_from_list(list_of_dictionary, key='name'):
    # key='name'
    result = []
    
    if type(list_of_dictionary)==type('as'):
        list_of_dictionary = ast.literal_eval(list_of_dictionary)
        # print('in str')

    for item in list_of_dictionary:
        result.append(item[key])
    
    return result

In [22]:
extracted_movie_features['genres_pro'] = extracted_movie_features['genres'].apply(extract_values_from_list)

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\1783868316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['genres_pro'] = extracted_movie_features['genres'].apply(extract_values_from_list)

In [23]:
extracted_movie_features.iloc[0].genres_pro

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

<h3>
    We will apply the same thing to the keywords column.
</h3>

In [24]:
extracted_movie_features['new_keywords'] = extracted_movie_features['keywords'].apply(extract_values_from_list)

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\3135794663.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['new_keywords'] = extracted_movie_features['keywords'].apply(extract_values_from_list)

In [25]:
extracted_movie_features['new_keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: new_keywords, Length: 4806, dtype: object

<h3>
    We will apply same function to the cast. But, as we are interested in the first 3 actors, we will again process the list of values obtain the trim it to first 3 values.
</h3>

In [26]:
extracted_movie_features['new_cast'] = extracted_movie_features['cast'].apply(extract_values_from_list)

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\127814833.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['new_cast'] = extracted_movie_features['cast'].apply(extract_values_from_list)

In [27]:
extracted_movie_features['new_cast']

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4806    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4807    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: new_cast, Length: 4806, dtype: object

In [28]:
extracted_movie_features['new_cast'] = extracted_movie_features['new_cast'].apply(lambda x: x[:3])

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\462147714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['new_cast'] = extracted_movie_features['new_cast'].apply(lambda x: x[:3])

In [29]:
extracted_movie_features['new_cast']

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: new_cast, Length: 4806, dtype: object

<h3>
    Now, fetching the value of the Director will require two operations: 
</h3>
<ol>
    <li>
        First to check whether the job is Director or not.
    </li>
    <li>
        Second, to append the name of the Director to the final list.
    </li>
</ol>

In [30]:
## Function for getting the name of the director

def fetch_name_of_director(list_of_dictionaries):

    result = []

    for item in ast.literal_eval(list_of_dictionaries):
        if item['job'] == 'Director':
            result.append(item['name'])

    return result

In [31]:
extracted_movie_features['new_crew'] = extracted_movie_features['crew'].apply(fetch_name_of_director)

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\423164455.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['new_crew'] = extracted_movie_features['crew'].apply(fetch_name_of_director)

In [32]:
extracted_movie_features['new_crew']

0                                [James Cameron]
1                               [Gore Verbinski]
2                                   [Sam Mendes]
3                            [Christopher Nolan]
4                               [Andrew Stanton]
                          ...
4804                          [Robert Rodriguez]
4805                              [Edward Burns]
4806                               [Scott Smith]
4807                               [Daniel Hsia]
4808    [Brian Herzlinger, Jon Gunn, Brett Winn]
Name: new_crew, Length: 4806, dtype: object

<h3>
    Now, checking for overview of the movies.
</h3>

In [33]:
extracted_movie_features.iloc[0].overview

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [34]:
## As the above data is in string, we will convert that into the list of separate strings in order
## to ease the tags creation part.

extracted_movie_features['new_overview'] = extracted_movie_features['overview'].apply(lambda x: x.split())

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\2754481149.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['new_overview'] = extracted_movie_features['overview'].apply(lambda x: x.split())

In [35]:
extracted_movie_features['new_overview']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: new_overview, Length: 4806, dtype: object

<br>
<h3>
    We will have to apply a transformation to the words processed and stored in the array form.
</h3>
<h3>
    We have to remove any spaces in the words, for e.g., New York -> NewYork.
</h3>
<h3>
    Why? Because it helps to create a better recommender system, as spaces may lead to unnecessary differentiation in the keywords. For e.g., Sam Worthington will have two tags: 'Sam', 'Worthington'; while, the Sam Mendes will also have two tags: 'Sam', 'Mendes'. Leading to unnecessary similarity between them.
</h3>
<br>

In [36]:
extracted_movie_features['genres_pro'] = extracted_movie_features['genres_pro'].apply(lambda x: [i.replace(" ", "") for i in x])

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\2733150007.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['genres_pro'] = extracted_movie_features['genres_pro'].apply(lambda x: [i.replace(" ", "") for i in x])

In [37]:
extracted_movie_features['genres_pro']

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres_pro, Length: 4806, dtype: object

In [38]:
extracted_movie_features['new_cast'] = extracted_movie_features['new_cast'].apply(lambda x: [i.replace(" ", "") for i in x])
extracted_movie_features['new_crew'] = extracted_movie_features['new_crew'].apply(lambda x: [i.replace(" ", "") for i in x])
extracted_movie_features['new_keywords'] = extracted_movie_features['new_keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
extracted_movie_features['new_overview'] = extracted_movie_features['new_overview'].apply(lambda x: [i.replace(" ", "") for i in x])

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\1006789308.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['new_cast'] = extracted_movie_features['new_cast'].apply(lambda x: [i.replace(" ", "") for i in x])
C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\1006789308.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['new_crew'] = extracted_movie_features['new_crew'].apply(lambda x: [i.replace(" ", "") for i in x])
C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\1006789308.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['new_keywords'] = extracted_movie_features['new_keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\1006789308.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['new_overview'] = extracted_movie_features['new_overview'].apply(lambda x: [i.replace(" ", "") for i in x])

In [39]:
extracted_movie_features

,movie_id,title,overview,genres,keywords,cast,crew,genres_pro,new_keywords,new_cast,new_crew,new_overview
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...","[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]","[BrianHerzlinger, JonGunn, BrettWinn]","[Ever, since, the, second, grade, when, he, fi..."

In [40]:
# Creating the new tags column
# Tags column is going to be the combination of genres, keywords, cast, crew

extracted_movie_features['tags'] = extracted_movie_features['genres_pro'] + extracted_movie_features['new_keywords'] + extracted_movie_features['new_cast'] + extracted_movie_features['new_crew']

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\2798185088.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted_movie_features['tags'] = extracted_movie_features['genres_pro'] + extracted_movie_features['new_keywords'] + extracted_movie_features['new_cast'] + extracted_movie_features['new_crew']

In [42]:
extracted_movie_features['tags']

0       [Action, Adventure, Fantasy, ScienceFiction, c...
1       [Adventure, Fantasy, Action, ocean, drugabuse,...
2       [Action, Adventure, Crime, spy, basedonnovel, ...
3       [Action, Crime, Drama, Thriller, dccomics, cri...
4       [Action, Adventure, ScienceFiction, basedonnov...
                              ...
4804    [Action, Crime, Thriller, unitedstates–mexicob...
4805    [Comedy, Romance, EdwardBurns, KerryBishé, Mar...
4806    [Comedy, Drama, Romance, TVMovie, date, loveat...
4807    [DanielHenney, ElizaCoupe, BillPaxton, DanielH...
4808    [Documentary, obsession, camcorder, crush, dre...
Name: tags, Length: 4806, dtype: object

In [43]:
## Creating a new dataframe which have only the movie_id, title, and tags

processed_movie_features = extracted_movie_features[['movie_id', 'title', 'tags']]

In [45]:
print(processed_movie_features.head())

   movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                tags
0  [Action, Adventure, Fantasy, ScienceFiction, c...
1  [Adventure, Fantasy, Action, ocean, drugabuse,...
2  [Action, Adventure, Crime, spy, basedonnovel, ...
3  [Action, Crime, Drama, Thriller, dccomics, cri...
4  [Action, Adventure, ScienceFiction, basedonnov...

<h3>
    Now, we will concatenate every element of the list into one whole string.
</h3>

In [46]:
processed_movie_features['tags'] = processed_movie_features['tags'].apply(lambda x: " ".join(x))

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\2427814388.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_movie_features['tags'] = processed_movie_features['tags'].apply(lambda x: " ".join(x))

In [47]:
processed_movie_features['tags']

0       Action Adventure Fantasy ScienceFiction cultur...
1       Adventure Fantasy Action ocean drugabuse exoti...
2       Action Adventure Crime spy basedonnovel secret...
3       Action Crime Drama Thriller dccomics crimefigh...
4       Action Adventure ScienceFiction basedonnovel m...
                              ...
4804    Action Crime Thriller unitedstates–mexicobarri...
4805    Comedy Romance EdwardBurns KerryBishé MarshaDi...
4806    Comedy Drama Romance TVMovie date loveatfirsts...
4807        DanielHenney ElizaCoupe BillPaxton DanielHsia
4808    Documentary obsession camcorder crush dreamgir...
Name: tags, Length: 4806, dtype: object

In [48]:
processed_movie_features.iloc[0].tags

'Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [50]:
## Converting everything to lowercase, i.e., we are pre-processing text in order to obtain better representation

processed_movie_features['tags'] = processed_movie_features['tags'].apply(lambda x: x.lower())

C:\Users\manishpra\AppData\Local\Temp\ipykernel_25840\1571108477.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_movie_features['tags'] = processed_movie_features['tags'].apply(lambda x: x.lower())

In [51]:
processed_movie_features['tags']

0       action adventure fantasy sciencefiction cultur...
1       adventure fantasy action ocean drugabuse exoti...
2       action adventure crime spy basedonnovel secret...
3       action crime drama thriller dccomics crimefigh...
4       action adventure sciencefiction basedonnovel m...
                              ...
4804    action crime thriller unitedstates–mexicobarri...
4805    comedy romance edwardburns kerrybishé marshadi...
4806    comedy drama romance tvmovie date loveatfirsts...
4807        danielhenney elizacoupe billpaxton danielhsia
4808    documentary obsession camcorder crush dreamgir...
Name: tags, Length: 4806, dtype: object

<br>
<h2>
    Text Vectorization
</h2>
<br></br>

In [52]:
 from sklearn.feature_extraction.text import CountVectorizer

In [53]:
 cv = CountVectorizer(max_features=5000, stop_words='english')

In [56]:
tag_vectors = cv.fit_transform(processed_movie_features['tags']).toarray()

In [57]:
tag_vectors.shape

(4806, 5000)

In [59]:
print(tag_vectors[0])

[0 0 0 ... 0 0 0]

In [62]:
## Most of the time, the matrix will be sparse, and it is because, it may depend on the type of movie
## it is vectorizing.

print("Most repeating names: ", cv.get_feature_names_out())

Most repeating names:  ['16thcentury' '17thcentury' '18thcentury' ... 'zoo' 'zooeydeschanel'
 'zoëkravitz']

In [ ]:
print("")